---
- name: Install oh-my-zsh
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"

- name: Ensure ZSH_CUSTOM is pointing to ~/.config/zsh 
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    regexp: '^# ZSH_CUSTOM=.*$'
    line: 'ZSH_CUSTOM=~/.config/zsh'
    state: present
